# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fd2ddae3-22da-45a5-b716-0b9a1c249f69";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-07df582e-c86c-4eaa-84c8-15bbb181c1bb".device = "/dev/disk/by-uuid/07df582e-c86c-4eaa-84c8-15bbb181c1bb";
  boot.initrd.luks.devices."luks-08cc3e78-1cbe-40d9-8ec3-6a035e051f11".device = "/dev/disk/by-uuid/08cc3e78-1cbe-40d9-8ec3-6a035e051f11";
  boot.initrd.luks.devices."luks-secondary" = {
    device = "/dev/disk/by-uuid/d88f69d2-7461-48c4-8069-5e56bd01f644";
  };

  boot.initrd.luks.reusePassphrases = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E184-48AC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/bigboy" = {
    device = "/dev/mapper/luks-secondary";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fc86796b-6e1e-41ba-bb9c-9d2f78d0871e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
