# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "xe" ];
  boot.kernelModules = [ "kvm-intel" "acpi_video" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [
    "xe.force_probe=7d45"
    "xe.enable_psr=0"
    "i2c_hid.debug=1"
    "pci=nocrs"
  ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    options i2c_hid_acpi polling_mode=1
  '';

  hardware.ipu6.enable = true;
  hardware.ipu6.platform = "ipu6epmtl";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b5f74117-03bd-4b40-a401-75bd2edcb007";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2e84878c-8284-40b8-ad7a-0e801e0fdb38".device = "/dev/disk/by-uuid/2e84878c-8284-40b8-ad7a-0e801e0fdb38";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D6A9-396C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
